name: CI-test

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check branch name
      if: github.ref == 'refs/heads/main'
      run: echo "Building on the main branch."
    - name: Do something
      run: echo "Doing something..."
